version: '3'
services:
  postgres:
    image: ankane/pgvector:latest
    container_name: pgvector-db
    environment:
      POSTGRES_USER: kevin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: patient_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
